---
deployment:
 tasks:
 - export DEPLOYPATH=/home/oppoldcx/public_html/
 - /bin/cp -R public/about_assets $DEPLOYPATH
 - /bin/cp -R public/blog_assets $DEPLOYPATH
 - /bin/cp -R public/contact_assets $DEPLOYPATH
 - /bin/cp -R public/css $DEPLOYPATH
 - /bin/cp -R public/dashboard_assets $DEPLOYPATH
 - /bin/cp -R public/images $DEPLOYPATH
 - /bin/cp -R public/js $DEPLOYPATH
 - /bin/cp -R public/loging $DEPLOYPATH
 - /bin/cp -R public/.htaccess $DEPLOYPATH
 - /bin/cp -R public/favicon.ico $DEPLOYPATH
 - /bin/cp -R public/mix-manifest.json $DEPLOYPATH
 - /bin/cp -R public/robots.txt $DEPLOYPATH
 - /bin/cp -R public/web.config $DEPLOYPATH 